import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import Header from '@/components/Header'
import SidebarLeft from '@/components/SidebarLeft'
import SidebarRight from '@/components/SidebarRight'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Counter-Strike 2 News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          <div className="relative min-h-screen flex flex-col items-center bg-transparent">
            <SidebarLeft />
            <SidebarRight />
            <main className="mx-auto px-4 py-8 w-full max-w-3xl z-10">
              {children} {/* Здесь отображается содержимое каждой страницы */}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  )
}
